### ISSUE TITLE
Migration to WebTransport!!

### ISSUE THREAD

**Issue by darioalessandro** [security-union/zoom-rs#19]
We will move away from websockets and use webtransport instead!!! 

I already added webtransport to wasm-bindgen: https://github.com/rustwasm/wasm-bindgen/pull/3344

I am working on adding webtransport to h3: https://github.com/hyperium/h3/pull/183

After this is done, we will have to swap our server.

**Comment by redoriental** [comment]
Looking forward to your success

**Comment by darioalessandro** [comment]
Thank you so much @redoriental the best thing is that this project will always be Open Source so that others can contribute to it!
