### ISSUE TITLE
Create Lightweight Docker Image

### ISSUE THREAD

**Issue by ImBIOS** [security-union/zoom-rs#68]
**Is your feature request related to a problem? Please describe.**
The current docker image built by `Dockerfile.actix` and `Dockerfile.yew` is huge because we use it for the active development process as runtime inside `docker-compose.yml`, it's not 'old device' friendly tho.

**Describe the solution you'd like**
We can create separated those `Dockerfile` and `docker-compose.yml` for development and production.

**Describe alternatives you've considered**
_undefined_

**Additional context**
https://levelup.gitconnected.com/create-an-optimized-rust-alpine-docker-image-1940db638a6c
https://dev.to/mohammadfaisal/how-i-reduced-docker-image-size-from-143-gb-to-224-mb-53nc

**Comment by griffobeid** [comment]
Great idea! Do you want to take on this task @ImBIOS ?

**Comment by darioalessandro** [comment]
They did!! https://github.com/security-union/zoom-rs/pull/69

**Comment by griffobeid** [comment]
Nice, some great improvements in #69, @ImBIOS do you want to add multistage builds as well? I think that would be best for a production env like gcloud where the VMs default to 10GB disks

**Comment by ImBIOS** [comment]
@griffobeid @darioalessandro Let me try to take this task more seriously, please assign me here.

**Comment by darioalessandro** [comment]
hahahah you got it @ImBIOS

**Comment by griffobeid** [comment]
This may give you trouble with the yew-ui image minification: https://github.com/security-union/zoom-rs/issues/72
