### ISSUE TITLE
Remove backend URL from UI dockerfile

### ISSUE THREAD

**Issue by darioalessandro** [security-union/zoom-rs#76]
1. Right now the UI dockerfile has the backend endpoint harcoded. 

This is bad because people will have to modify this image to change that value to host it elsewhere.

 
<img width="3008" alt="Screenshot 2023-06-19 at 2 44 38 PM" src="https://github.com/security-union/zoom-rs/assets/1176339/e0735e8d-d9bb-4d6e-8e1f-f566e0aed8df">

Modify the build process so that the UI App accepts the parameter at runtime, if this is impossible, then document this kink so that others are aware of it.

**Comment by griffobeid** [comment]
#72
